### PR TITLE
SLE44xx serial protocol decoder

### PR DESCRIPTION
**Pull request by ceres-c**
This is a simple (and perfectible) protocol decoder for Siemens/Infineon SLE 4418/28/32/42 memory cards serial protocol.
ATR, commands and data packets are separated and reset/abort events marked independently. LSB data streams are decoded.

Example output can be seen here: https://github.com/ceres-c/SLExx-Sigrok

As discussed on the mailing list I'm not able to provide test dumps because the system I was working on was not public.
I've bought some blank cards and I'll post a dump of those as soon as I get them from china.

### CODE REVIEW

**Comment by abraxa** [comment]
Note: example dumps will be provided as mentioned at https://github.com/ceres-c/SLExx-Sigrok/issues/1

**Comment by gsigh** [comment]
The availability of captures is a necessity for integration of the decoder and future maintenance. I will start working on that PR when example dumps become available. Got a checklist what to address, but currently cannot check for regressions after changes.

Can you check the doc on the validity of the data bits? The .wait() conditions in the .decode() method suggest that data bits are valid for the period of time where CLK is high. Can you confirm that? This would obsolete the "estimation" of a bit slot's width.

**Comment by ceres-c** [comment]
I've finally uploaded the necessary dumps https://github.com/sigrokproject/sigrok-dumps/pull/28

**Comment by gsigh** [comment]
Have seen the samples, which cover memory read and write. Answer to RESET may not fully be covered (incomplete RST pulse including CLK)?

Have started some adjustment on top of your initial implementation, but will take time to complete these. Thank you for what you did so far.

**Comment by gsigh** [comment]
Merged in 7e87b2f75223, thank you. Have rephrased the commit message to better match the project's tradition. Have put more adjustment and some extensions on top of your initial version. Some of the code paths are untested, minor TODO items remain.

**Comment by ceres-c** [comment]
I took a look at your improvements and you've done a terrific job there! This is exactly what I meant when I wrote "perfectible" :)

**Pull request closed without merging**
