### PR TITLE
onewire: add DS2408 decoder

### PR DESCRIPTION
**Pull request by manio**
It is a 1-Wire 8-Channel Addressable Switch
datasheet: https://datasheets.maximintegrated.com/en/ds/DS2408.pdf

### CODE REVIEW

**Comment by uwehermann** [comment]
Hi, looks good, will have a closer look soonish. In the mean time, do you happen to have a few sample *.sr files of DS2408 traffic for the sigrok-dumps repo? We're collecting .sr files there for manual testing + review, and also automatic regression-testing via the sigrok-test repo.

**Comment by uwehermann** [comment]
(same goes for the "Resume ROM" command, in case we don't already have a sample in sigrok-dumps)

**Comment by manio** [comment]
Thanks, I added the dumps: https://github.com/sigrokproject/sigrok-dumps/pull/6

**Comment by uwehermann** [comment]
Merged in 8d63f8a496f009829b285f06e42eb45377c45540 with some small cosmetics, thanks a lot!

**Pull request closed without merging**
