### PR TITLE
added caliper decoder

### PR DESCRIPTION
**Pull request by Harvie**
image

image

http://www.shumatech.com/support/chinese_scales.htm
https://www.instructables.com/id/Reading-Digital-Callipers-with-an-Arduino-USB/

### CODE REVIEW

**Comment by Harvie** [comment]
Any news? This pull request should be a no-brainer...

**Comment by abraxa** [comment]
Merged in https://sigrok.org/gitweb/?p=libsigrokdecode.git;a=commit;h=5ed5cea580fe8bc9405043b216eb420792889283, thanks!

My apologies that it took a while, won't happen next time.

**Comment by Harvie** [comment]
Thanks.
I've added brief note on sigrok wiki: https://sigrok.org/wiki/Protocol_decoder:Caliper

**Comment by abraxa** [comment]
Awesome, thank you!

**Pull request closed without merging**
