### PR TITLE
i2s: Fix 2 issues.

### PR DESCRIPTION
**Pull request by waveletboy**
1. WS = 0, Left Channel; WS = 1, Right Channel
2. Data start and end at falling edge of SCK

### CODE REVIEW

**Comment by uwehermann** [comment]
Looks good, thanks! Merged in c78c8f6faf51eb5fa66dd2ca94439b40ad1047b0.

**Comment by uwehermann** [comment]
Oh, forgot to mention: I've also updated the sigrok-test repo to match the new decoder output.

If you have any additional i2c example files (*.sr) for our sigrok-dumps repo, that would also be great (for greater test-coverage).

**Comment by waveletboy** [comment]
I have a 16bit 48khz I2S sample. Will upload once I have time. The other thing I noticed is that the I2S sample 2ch-16bit-16khz.sr is actually 32bit 8khz.

**Comment by uwehermann** [comment]
Hi, did you get a chance to grab another i2s *.sr file for our sigrok-dumps repo btw?

**Comment by waveletboy** [comment]
Hi Uwe, please see https://github.com/sigrokproject/sigrok-dumps/pull/15

**Comment by waveletboy** [comment]
Hi Uwe,

I just closed #15 and created new one
https://github.com/sigrokproject/sigrok-dumps/pull/16 which has better
samples.

**Pull request closed without merging**
