### PR TITLE
timing pd.py modifications to add configurability on "Timing;Time" display depending on Data Level (Both, 1 or 0) 

### PR DESCRIPTION
**Pull request by bvernoux**
libsigrokdecode decoders timing pd.py modifications to add configurability on "Timing;Time" display depending on Data Level (Both, 1 or 0)

### CODE REVIEW

**Comment by bvernoux** [comment]
The modifications are very easy to check and without any regression why such Pull Request is not merged ?

**Comment by depili** [comment]
Commit message should be reworked, the projects style expects the format of:
```
timing: add data level configuration

description of why, how and where the change was done
```

Also having test dumps and ideally test cases for it in the test repo would help

**Comment by abraxa** [comment]
Hi, thanks for the change. Please help me understand the use case for it. Why would someone want to see both edges but only have the timing decoder show the time for either rising or falling edge? Why not simply select the rising or falling edge as the source of the timing?

**Comment by bvernoux** [comment]
The aim is to have possibility to check Timing on Rising, Falling or Both Edges
The modifications are very basic and work fine

**Comment by abraxa** [comment]
Thanks for your response. The main issue for me is that the timing PD has been reworked since you created the PR and merging is no longer trivial. Hence I wonder if it's worth the effort of rebasing or not. If you are willing to rebase it then I'd certainly welcome it.

**Pull request closed without merging**
