### PR TITLE
decoders: Add cJTAG oscan1 decoder

### PR DESCRIPTION
**Pull request by diodep**

### CODE REVIEW

**Comment by uwehermann** [comment]
Hi, thanks for the PR! Could you please add a few *.sr files to our sigrok-dumps repo that the decoder can be tested against? Ideally also test-cases in the sigrok-test repo, if possible.

I don't know much about cJTAG, is it very similar to either JTAG or EJTAG (we have decoders for those two)? If yes, could it make sense to extend one of the other decoders, or maybe make cJTAG a decoder that stacks on onw of the two?

**Comment by diodep** [comment]
@uwehermann In fact, CJTAG decoder can act as regular JTAG decoder. If somebody wants to make it stacks, then he should make JTAG stacks on CJTAG. Because CJTAG has 2-wire mode. It is necessary to extract regular JTAG status from CJTAG packet.

I tested it out by dreamsourcelab's DSView. Right now I don't know how to convert DSL file to SR file. Could you help me out?

**Comment by uwehermann** [comment]
Haven't really looked at the DSL file format, not sure if they use the sigrok format or not (or whether they modified it). If you can grab a few new .sr files in PulseView that's probably simplest. Otherwise, please add some DSL example captures to sigrok-dumps, I'll see if I can easily convert them, if needed.

**Comment by diodep** [comment]
> Haven't really looked at the DSL file format, not sure if they use the sigrok format or not (or whether they modified it). If you can grab a few new .sr files in PulseView that's probably simplest. Otherwise, please add some DSL example captures to sigrok-dumps, I'll see if I can easily convert them, if needed.

https://iloli.bid/cjtag-n305-sba.dsl
https://iloli.bid/cjtag-n307-sba%20test.dsl

**Comment by uwehermann** [comment]
Thanks! I've converted the files and slightly shortened them in commit bcb3664abca5138420761c0713cee916b06fd314 in the sigrok-dumps repo.

I've also renamed some channel names, I'm relatively sure that TDO is rather TMSC, and all channels apart from TCKC/TMSC are unused, so I dropped those.

If you have some time, could you please add a small README for the files, which gives some info about which devices and cJTAG tools were used and what the data roughly contains etc.?

Example:
https://github.com/sigrokproject/sigrok-dumps/blob/master/jtag/olimex_stm32-h103/README

**Comment by uwehermann** [comment]
The decoder is now merged with various changes (see below), thanks a lot!

The name is "cjtag" (ID and directory name) or "cJTAG" (name) now, I dropped the "OSCAN1" since it might gain further support later. The directory name was "cjtag-oscan0" in your original commit, not sure why. Should it have been "cjtag-oscan1" maybe?

Your PD was based on some non-mainline DSView state of the "jtag" decoder that has diverged from the mainline PD from libsigrokdecode. I've taken the liberty to "rebase" your decoder on top of the current mainline jtag PD, I hope you don't mind. This gives a clear overview of what the changes are vs. the jtag PD, in case we have to perform changes on both PDs later, or in case we want to merge both PDs later on.

In commit e88f63751affb679a894ed2c81e1b750aa70fd61 I made an exact copy of the jtag PD, and added your changes in commit e349cbe9c80b772d5b96c94d24719b2cb49e0c4f (with minor whitespace/cosmetic changes squashed in).

There are a few additional commits on top, some only cosmetic. One of them drops the unused channels (TDI/TDO/etc.) since cJTAG only has TCKC/TMSC as far as I know (there's still some code paths which might use invalid TDI/TDO/etc. values maybe? not sure, might need more investigation). 

Another commit correctly names those TCKC/TMSC channels.

One other commit puts each cJTAG state in an extra annotation class, so they can be easily distinguished on the command-line and also graphically (e.g. based on color) in PulseView. Or they can be shown/hidden per annotation-class in PulseView. Example: https://imgur.com/a/aw1LZQ9

You changed the default JTAG state from 'RUN-TEST/IDLE' to 'TEST-LOGIC-RESET', but that doesn't seem to make any difference (at least for the files you provided), so I kept the original default to stay closer to the jtag PD state.

I've added two small test-cases in 8cca9c0f06dcba7034e6b36f0f3edc77149dce2f in the sigrok-test repo (based on the files you provided).

**Comment by diodep** [comment]
Yes, it should be OSCAN1, I need to fix the typo :D

**Comment by diodep** [comment]
> Thanks! I've converted the files and slightly shortened them in commit bcb3664abca5138420761c0713cee916b06fd314 in the sigrok-dumps repo.
> 
> I've also renamed some channel names, I'm relatively sure that TDO is rather TMSC, and all channels apart from TCKC/TMSC are unused, so I dropped those.
> 
> If you have some time, could you please add a small README for the files, which gives some info about which devices and cJTAG tools were used and what the data roughly contains etc.?
> 
> Example:
> https://github.com/sigrokproject/sigrok-dumps/blob/master/jtag/olimex_stm32-h103/README

Thank you for your optimization. Btw, cJTAG has optional TDIC/TDOC/nTRSTC channel (on 1149.7 T4 wide/T5 wide TAP), so you can add it to the decoder as optional channel.

In fact, you can even merge this plugin to original JTAG decoder plugin if you add these optional channel, because it is a improvement and drop-in replacement of original JTAG decoder.

I'm too busy recently, when I have spare time, I will start support of ZBS/Selection Escape/OSCAN0-7/J-Scan and Multi-drop on this decoder plugin.

Thank you for your work.

**Pull request closed without merging**
